In [1]:
import numpy as np
import pandas as pd

In [13]:
# create list

list1 = [1,2,3,4]
list2 = [-1,-2,-3,-4]
list3 = [ list1, list2  ]
print(list3)

[[1, 2, 3, 4], [-1, -2, -3, -4]]


In [3]:
# ar_list1 =  array("i", list1)  # doesnt work

In [4]:
# list to array

array1 = np.array(list1)
print(array1)

[1 2 3 4]


In [26]:
print(sum(array1))
print(array1[0])

10
1


In [16]:
dimArray = np.array( list3 )

In [28]:
print ( dimArray )

[[ 2  3  4  5]
 [ 0 -1 -2 -3]]


In [22]:
print( dimArray[1][0] )

-1


In [27]:
#increrment all by 1
dimArray = dimArray +1

In [5]:
# list to series ( with default index )
print ( pd.Series(list1) )

# array to series also works 
print ( pd.Series(array1) )

0    1
1    2
2    3
3    4
dtype: int64
0    1
1    2
2    3
3    4
dtype: int32


In [6]:
# Series with explicit index
#print ( pd.Series(array1, index=['zero', 'one', 'two', 'three']) )

indexedSeries = pd.Series(array1, index=['zero', 'one', 'two', 'three'])

In [7]:
print(indexedSeries)

zero     1
one      2
two      3
three    4
dtype: int32
