In [1]:
import numpy as np
import pandas as pd

In [2]:
# create list

list1 = [1,2,3,4]
list2 = [-1,-2,-3,-4]
list3 = [ list1, list2  ]
print(list3)

[[1, 2, 3, 4], [-1, -2, -3, -4]]


In [3]:
# ar_list1 =  array("i", list1)  # doesnt work

In [4]:
# list to array

array1 = np.array(list1)
print(array1)

[1 2 3 4]


In [5]:
print(sum(array1))
print(array1[0])

10
1


In [6]:
dimArray = np.array( list3 )

In [7]:
print ( dimArray )

[[ 1  2  3  4]
 [-1 -2 -3 -4]]


In [8]:
print( dimArray[1][0] )

-1


In [9]:
#increrment all by 1
dimArray = dimArray +1

In [10]:
# list to series ( with default index )
print ( pd.Series(list1) )

# array to series also works 
print ( pd.Series(array1) )

0    1
1    2
2    3
3    4
dtype: int64
0    1
1    2
2    3
3    4
dtype: int32


In [11]:
# Series with explicit index
#print ( pd.Series(array1, index=['zero', 'one', 'two', 'three']) )

indexedSeries = pd.Series(array1, index=['zero', 'one', 'two', 'three'])

In [12]:
print(indexedSeries)

zero     1
one      2
two      3
three    4
dtype: int32


In [20]:
df = pd.DataFrame([
  ['col1', 'col2', 'col3', 'col4', 'col5'], # this (column names in row) is an allowable alternative to the columns arg
    ['January', 100, 100, 23, 100],
  ['February', 51, 45, 145, 45],
  ['March', 81, 96, 65, 96],
  ['April', 80, 80, 54, 180],
  ['May', 51, 54, 54, 154],
  ['June', 112, 109, 79, 129]],
    columns=['month', 'clinic_east',
           'clinic_north', 'clinic_south',
           'clinic_west']
 )

In [28]:
print(df)
print(df.clinic_east[0])
print(type(df.clinic_east[0]))
print(df.info())

      month clinic_east clinic_north clinic_south clinic_west
0      col1        col2         col3         col4        col5
1   January         100          100           23         100
2  February          51           45          145          45
3     March          81           96           65          96
4     April          80           80           54         180
5       May          51           54           54         154
6      June         112          109           79         129
col2
<class 'str'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   month         7 non-null      object
 1   clinic_east   7 non-null      object
 2   clinic_north  7 non-null      object
 3   clinic_south  7 non-null      object
 4   clinic_west   7 non-null      object
dtypes: object(5)
memory usage: 408.0+ bytes
None


In [33]:
print ( df.iloc[2] ) # this iloc[][] is an xref - nice tool
#print ( df.iloc[2][2] ) 

month           February
clinic_east           51
clinic_north          45
clinic_south         145
clinic_west           45
Name: 2, dtype: object
