In [1]:
import numpy as np
import pandas as pd

In [2]:
# create list

list1 = [1,2,3,4]
list2 = [-1,-2,-3,-4]
list3 = [ list1, list2  ]
print(list3)

[[1, 2, 3, 4], [-1, -2, -3, -4]]


In [3]:
# ar_list1 =  array("i", list1)  # doesnt work

In [4]:
# list to array

array1 = np.array(list1)
print(array1)

[1 2 3 4]


In [5]:
print(sum(array1))
print(array1[0])

10
1


In [6]:
dimArray = np.array( list3 )

In [7]:
print ( dimArray )

[[ 1  2  3  4]
 [-1 -2 -3 -4]]


In [8]:
print( dimArray[1][0] )

-1


In [9]:
#increrment all by 1
dimArray = dimArray +1

In [10]:
# list to series ( with default index )
print ( pd.Series(list1) )

# array to series also works 
print ( pd.Series(array1) )

0    1
1    2
2    3
3    4
dtype: int64
0    1
1    2
2    3
3    4
dtype: int32


In [11]:
# Series with explicit index
#print ( pd.Series(array1, index=['zero', 'one', 'two', 'three']) )

indexedSeries = pd.Series(array1, index=['zero', 'one', 'two', 'three'])

In [12]:
print(indexedSeries)

zero     1
one      2
two      3
three    4
dtype: int32


In [13]:


df = pd.DataFrame([
  ['January', 100, 100, 23, 100],
  ['February', 51, 45, 145, 45],
  ['March', 81, 96, 65, 96],
  ['April', 80, 80, 54, 180],
  ['May', 51, 54, 54, 154],
  ['June', 112, 109, 79, 129]],
  columns=['month', 'clinic_east',
           'clinic_north', 'clinic_south',
           'clinic_west']
)

In [14]:
print(df)

      month  clinic_east  clinic_north  clinic_south  clinic_west
0   January          100           100            23          100
1  February           51            45           145           45
2     March           81            96            65           96
3     April           80            80            54          180
4       May           51            54            54          154
5      June          112           109            79          129


In [15]:
# slice rows : these give the same output

print(df[1:3])
print(df.iloc[1:3]) 

      month  clinic_east  clinic_north  clinic_south  clinic_west
1  February           51            45           145           45
2     March           81            96            65           96
      month  clinic_east  clinic_north  clinic_south  clinic_west
1  February           51            45           145           45
2     March           81            96            65           96


In [16]:
# slice rows : these also give the same output

print(df[ 3: ])
print(df[ -3: ])


   month  clinic_east  clinic_north  clinic_south  clinic_west
3  April           80            80            54          180
4    May           51            54            54          154
5   June          112           109            79          129
   month  clinic_east  clinic_north  clinic_south  clinic_west
3  April           80            80            54          180
4    May           51            54            54          154
5   June          112           109            79          129


In [17]:
# try skip step 
## [ start : end : interval ] 

df[0:4:2] # doesnt work with a straight slice
#df.iloc[0:4]

month  clinic_east  clinic_north  clinic_south  clinic_west
0  January          100           100            23          100
2    March           81            96            65           96

In [18]:
# instruction

april_may_june = df[ 3: ]

april_may_june

month  clinic_east  clinic_north  clinic_south  clinic_west
3  April           80            80            54          180
4    May           51            54            54          154
5   June          112           109            79          129

In [19]:
#########
## Select with conditions
###############

In [20]:
df = pd.DataFrame([
  ['January', 100, 100, 23, 100],
  ['February', 51, 45, 145, 45],
  ['March', 81, 96, 65, 96],
  ['April', 80, 80, 54, 180],
  ['May', 51, 54, 54, 154],
  ['June', 112, 109, 79, 129]],
  columns=['month', 'clinic_east',
           'clinic_north', 'clinic_south',
           'clinic_west'])

In [21]:
#df

In [22]:
# lambda refresher

f = lambda n : n * 5
f(3)

15

In [23]:
# select WHERE, single condition
# df[ df.column <op> condition ]

df[ df.clinic_east > 51 ]

month  clinic_east  clinic_north  clinic_south  clinic_west
0  January          100           100            23          100
2    March           81            96            65           96
3    April           80            80            54          180
5     June          112           109            79          129

In [24]:
## instruction
# Create variable january using a logical statement that selects the row of df where the 'month' column is 'January'. 

january = df[ df.month ==  'January' ]

In [25]:
# select WHERE, multiple conditions
# df[  ( df.column <op> condition )  |/& ( df.column <op> condition ) ]
## * for more than 2 conditions, AND (&) is evaluated before OR (|) 


In [26]:
## instruction
# Create the variable march_april, which contains the data from March and April. Do this using two logical statements combined using |, which means “or”.

march_april = df[ ( df.month == 'March' ) | ( df.month == 'April' ) ]

print(march_april)

   month  clinic_east  clinic_north  clinic_south  clinic_west
2  March           81            96            65           96
3  April           80            80            54          180


In [27]:
# select WHERE, using ISIN

# df[df.<column>.isin([value, value, value])]

In [28]:
df[df.clinic_east.isin([80, 81])]

month  clinic_east  clinic_north  clinic_south  clinic_west
2  March           81            96            65           96
3  April           80            80            54          180

In [29]:
## instruction
# Create the variable january_february_march, containing the data from January, February, and March. Do this using a single logical statement with the isin command.

january_february_march = df[df.month.isin(['January', 'February', 'March'])]

print(january_february_march)


      month  clinic_east  clinic_north  clinic_south  clinic_west
0   January          100           100            23          100
1  February           51            45           145           45
2     March           81            96            65           96


In [30]:
# Reset index on extracted slice

In [31]:
df[ df.clinic_east == 51 ]

# notice the index 1,4 is fragmented

month  clinic_east  clinic_north  clinic_south  clinic_west
1  February           51            45           145           45
4       May           51            54            54          154

In [32]:
df[ df.clinic_east == 51 ].reset_index()

# FIXED, sorta, though old values remain in a new column, index

index     month  clinic_east  clinic_north  clinic_south  clinic_west
0      1  February           51            45           145           45
1      4       May           51            54            54          154

In [33]:
df[ df.clinic_east == 51 ].reset_index( drop = True )  # drop = True removes the old index values

month  clinic_east  clinic_north  clinic_south  clinic_west
0  February           51            45           145           45
1       May           51            54            54          154

In [34]:
# Note, both these operations create a new dataframe with the result set. 'df' is not effected.
#df

In [35]:
# use inplace=True to modify a dataframe in place

df[ df.clinic_east < 80 ].reset_index(inplace=True   )

In [36]:
df

month  clinic_east  clinic_north  clinic_south  clinic_west
0   January          100           100            23          100
1  February           51            45           145           45
2     March           81            96            65           96
3     April           80            80            54          180
4       May           51            54            54          154
5      June          112           109            79          129

In [37]:
# New method :: loc[] to access rows
df.loc[[1, 3, 5]]

#df.loc[[1, 3, 5]].reset_index()

month  clinic_east  clinic_north  clinic_south  clinic_west
1  February           51            45           145           45
3     April           80            80            54          180
5      June          112           109            79          129

In [38]:
df2 = df.loc[[1, 3, 5]]
df2


month  clinic_east  clinic_north  clinic_south  clinic_west
1  February           51            45           145           45
3     April           80            80            54          180
5      June          112           109            79          129

In [39]:
## instruction
# Create a new DataFrame called df3 by resetting the indices on df2 (don’t use inplace or drop). Did df2 change after you ran this command?

df3 = df2.reset_index()
df3

index     month  clinic_east  clinic_north  clinic_south  clinic_west
0      1  February           51            45           145           45
1      3     April           80            80            54          180
2      5      June          112           109            79          129

In [40]:
# Reset the indices of df2 by using the keyword inplace=True and drop=True. Did the indices of df2 change? How is df2 different from df3?

df2.reset_index(drop=True, inplace=True)
df2

month  clinic_east  clinic_north  clinic_south  clinic_west
0  February           51            45           145           45
1     April           80            80            54          180
2      June          112           109            79          129

In [41]:
###
#  Excursion : using reset_index() to force a numeric index on a df that has been indexed on another non-numeric column
####

#df_networkProject = pd.read_csv('Nodes_IN_Medium.csv')

In [42]:
#type(df_networkProject)
#df_networkProject.head(5)

In [43]:
# set the df index to nodename

#df_networkProject.set_index('nodename', inplace = True)

In [44]:
# now reset the index

#df_networkProject.reset_index(inplace=True)

# WORKS!

In [45]:
####################
# Exercise
#################

#In this example, you’ll be the data analyst for ShoeFly.com, a fictional online shoe store. You’ve seen this data; now it’s your turn to work with it!

In [46]:
# Load the data from shoefly.csv into the variable orders 

#orders = pd.read_csv('shoefly.csv')

In [47]:
# Inspect the first 5 lines of the data.

#orders.head(5) # no good; Excel didnt parse it; its all in 1 column... FIXED

In [48]:
# Select all of the email addresses from the column email and save them to a variable called emails

#orders['email']

In [49]:
# Frances Palmer claims that her order was wrong. What did Frances Palmer order? Use logic to select that row of orders and save it to the variable frances_palmer

#frances_palmer = orders[ ( orders.first_name  == 'Frances' ) & ( orders.last_name == 'Palmer'  )  ]
#print(type(frances_palmer))  # even this single line result is of type data frame
#frances_palmer

In [50]:
# We need some customer reviews for our comfortable shoes. Select all orders for shoe_type: clogs, boots, and ballet flats and save them to the variable comfy_shoes.

#comfy_shoes = orders[ orders.shoe_type.isin(  [ 'clogs', 'boots', 'ballet flats' ] ) ]

#print( comfy_shoes )
#comfy_shoes

In [51]:
##############
# Modifying a DataFrame
#################

In [52]:
## Adding a Column I

In [53]:
df = pd.DataFrame([
  [1, '3 inch screw', 0.5, 0.75],
  [2, '2 inch nail', 0.10, 0.25],
  [3, 'hammer', 3.00, 5.50],
  [4, 'screwdriver', 2.50, 3.00]
],
  columns=['Product ID', 'Description', 'Cost to Manufacture', 'Price']
)

In [54]:
# The DataFrame df contains information on products sold at a hardware store. Add a column to df called 'Sold in Bulk?', which indicates if the product is sold in bulk or individually. The final table should look like this:

In [55]:
df['Sold in Bulk?'] = [ 'Yes', 'Yes', 'No', 'No' ]

In [56]:
# Add a column to df called Is taxed?, which indicates whether or not to collect sales tax on the product. It should be 'Yes' for all rows.

In [57]:
df['Is taxed?'] = 'Yes'

In [62]:
## Using apply() to modify a column

df['Is taxed?'] = df["Is taxed?"].apply(str.upper) # dot . notation can be used to designate columns by exact name , only w/o whitespace

In [63]:
df

Product ID   Description  Cost to Manufacture  Price Sold in Bulk?  \
0           1  3 inch screw                  0.5   0.75           Yes   
1           2   2 inch nail                  0.1   0.25           Yes   
2           3        hammer                  3.0   5.50            No   
3           4   screwdriver                  2.5   3.00            No   

  Is taxed?  
0       YES  
1       YES  
2       YES  
3       YES